### ISSUE TITLE
Got error when running download_image.py

### ISSUE THREAD

**Issue by zcrwind** [JudyYe/zero-shot-gcn#14] opened 2019-03-04 08:33 UTC
I have registered ImageNet and got the accesskey. However, when I run the `download_image.py`, I obtained the error `!!! Error when downloading nxxxx`, where `xxxx` is the wnid. I wanna helps from you guys, many thanks!

**Comment by khtam** [comment] 2019-03-23 06:32
same problem, @JudyYe is the has the ImageNet dataset changed or something else wrong? the original URL points to a 'URL not valid' page.

**Comment by JudyYe** [comment] 2019-03-23 13:46
Hi, 

Thanks for reporting the isues. 

The API in the [code](https://github.com/JudyYe/zero-shot-gcn/blob/master/src/tools/download_image.py#L16) is based on ImageNet doc: [how to download by HTTP protocol](http://image-net.org/download-images), which should (and did) return a tar file containing all images in that wnid.

However, Imagenet is under maintenance recently. 
<img width="979" alt="Screen Shot 2019-03-23 at 9 33 51 AM" src="https://user-images.githubusercontent.com/12457136/54866816-0bf6f580-4d4f-11e9-9d4e-916c846c4cd5.png">

This probably causes massive invalid URL under this API. (358/1000 in imagenet1k and 1511/1549 in 2-hops.) 


A possible workaround is firstly requesting url list
```http://www.image-net.org/api/text/imagenet.synset.geturls?wnid=[wnid]```
 and then download url one by one. The potential issue is that massive urls have been  reported invalid due to Imagenet has been online for 10 years.  I am not sure if the fraction of invalid images is significant enough to affect the evaluation. You may refer to [this](https://github.com/Tencent/tencent-ml-images/issues/12) for further details.

Thanks.

**Comment by JGyoung33** [comment] 2019-05-11 06:24
> Hi,
> 
> Thanks for reporting the isues.
> 
> The API in the [code](https://github.com/JudyYe/zero-shot-gcn/blob/master/src/tools/download_image.py#L16) is based on ImageNet doc: [how to download by HTTP protocol](http://image-net.org/download-images), which should (and did) return a tar file containing all images in that wnid.
> 
> However, Imagenet is under maintenance recently.
> <img alt="Screen Shot 2019-03-23 at 9 33 51 AM" width="979" src="https://user-images.githubusercontent.com/12457136/54866816-0bf6f580-4d4f-11e9-9d4e-916c846c4cd5.png">
> 
> This probably causes massive invalid URL under this API. (358/1000 in imagenet1k and 1511/1549 in 2-hops.)
> 
> A possible workaround is firstly requesting url list
> `http://www.image-net.org/api/text/imagenet.synset.geturls?wnid=[wnid]`
> and then download url one by one. The potential issue is that massive urls have been reported invalid due to Imagenet has been online for 10 years. I am not sure if the fraction of invalid images is significant enough to affect the evaluation. You may refer to [this](https://github.com/Tencent/tencent-ml-images/issues/12) for further details.
> 
> Thanks.

Hi, I met the same problem, and the error is: URL is invalid. It's very regretful that reproduction failed because of this error.

**Comment by joanconquerlee** [comment] 2019-10-09 08:00
Hi,
I also met the same problem. Only a few classes can be downloaded. So does it mean that I can't reproduce it cause this error? crying...

**Comment by kaiqiangh** [comment] 2019-10-30 13:18
@joanconquerlee Hi, I tried to download images, but I cannot even download one images. Do i need to modify some codes, such as urllib?

**Comment by JudyYe** [comment] 2020-07-30 01:33
It is the problem of Imagenet maintenance. Please direct to ImageNet team. I am afraid I cannot help y'all right now.  
I'm closing this issue.

**Closed as completed by JudyYe** 2020-07-30 01:33 UTC

**Comment by JudyYe** [comment] 2021-07-21 17:03
Hi, just some updates. ImageNet official website seems back to life. https://image-net.org/
